/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package var;

import static var.SelectSubjectMenu.subj1;
import static var.SelectSubjectMenu.subj2;
import static var.SelectSubjectMenu.subj3;
import static var.SelectSubjectMenu.subj4;
import static var.SelectSubjectMenu.subj5;

/**
 *
 * @author GP62
 */
public class CheckAttendancePercentage extends javax.swing.JFrame {

    /**
     * Creates new form CheckAttendancePercentage
     */
    public static String subj1=new String();
    public static String subj2=new String();
    public static String subj3=new String();
    public static String subj4=new String();
    public static String subj5=new String();
    public static String USN=new String();
    public static String StudentNameFound=new String();
    
    float subj1Perc,subj2Perc,subj3Perc,subj4Perc,subj5Perc,totalPerc;
    
    public CheckAttendancePercentage(String Sub1,String Sub2,String Sub3,String Sub4,String Sub5,String usn) {
        
        subj1=Sub1;
        subj2=Sub2;
        subj3=Sub3;
        subj4=Sub4;
        subj5=Sub5;
        USN=usn;
        subj1Perc=DatabaseConnection.subjectWiseAttendanceCalculation(subj1, USN);
        subj2Perc=DatabaseConnection.subjectWiseAttendanceCalculation(subj2, USN);
        subj3Perc=DatabaseConnection.subjectWiseAttendanceCalculation(subj3, USN);
        subj4Perc=DatabaseConnection.subjectWiseAttendanceCalculation(subj4, USN);
        subj5Perc=DatabaseConnection.subjectWiseAttendanceCalculation(subj5, USN);
        totalPerc=DatabaseConnection.totalAttendanceCalculations(USN);
        StudentNameFound=DatabaseConnection.getStudentName(USN);
        
        myinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Sub3 = new javax.swing.JTextField();
        Sub2 = new javax.swing.JTextField();
        Sub1Percentage = new javax.swing.JTextField();
        Sub5Percentage = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Sub5 = new javax.swing.JTextField();
        Sub4Percentage = new javax.swing.JTextField();
        Sub1 = new javax.swing.JTextField();
        Sub4 = new javax.swing.JTextField();
        TotalPercentage = new javax.swing.JTextField();
        UsnLabel = new javax.swing.JLabel();
        Sub3Percentage = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        Sub2Percentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sub3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub3ActionPerformed(evt);
            }
        });

        Sub2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub2ActionPerformed(evt);
            }
        });

        Sub1Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub1Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub1Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1PercentageActionPerformed(evt);
            }
        });

        Sub5Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub5Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub5Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub5PercentageActionPerformed(evt);
            }
        });

        Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        Sub5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub5ActionPerformed(evt);
            }
        });

        Sub4Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub4Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub4Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub4PercentageActionPerformed(evt);
            }
        });

        Sub1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1ActionPerformed(evt);
            }
        });

        Sub4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub4ActionPerformed(evt);
            }
        });

        TotalPercentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalPercentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPercentageActionPerformed(evt);
            }
        });

        UsnLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        UsnLabel.setForeground(new java.awt.Color(204, 204, 204));
        UsnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Sub3Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub3Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub3Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub3PercentageActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Harlow Solid Italic", 3, 52)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(204, 204, 204));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Sub2Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub2Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub2Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub2PercentageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Total)
                            .addComponent(Sub5)
                            .addComponent(Sub4)
                            .addComponent(Sub3)
                            .addComponent(Sub1)
                            .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sub3Percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(Sub4Percentage)
                            .addComponent(Sub5Percentage)
                            .addComponent(TotalPercentage)
                            .addComponent(Sub2Percentage)
                            .addComponent(Sub1Percentage, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub1Percentage)
                    .addComponent(Sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub2Percentage)
                    .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub3Percentage)
                    .addComponent(Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub4Percentage)
                    .addComponent(Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub5Percentage)
                    .addComponent(Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane1.setLayer(Sub3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub1Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub5Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Total, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub4Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TotalPercentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(UsnLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub3Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(NameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub2Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void myinitComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Sub3 = new javax.swing.JTextField();
        Sub2 = new javax.swing.JTextField();
        Sub1Percentage = new javax.swing.JTextField();
        Sub5Percentage = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Sub5 = new javax.swing.JTextField();
        Sub4Percentage = new javax.swing.JTextField();
        Sub1 = new javax.swing.JTextField();
        Sub4 = new javax.swing.JTextField();
        TotalPercentage = new javax.swing.JTextField();
        UsnLabel = new javax.swing.JLabel();
        Sub3Percentage = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        Sub2Percentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sub3.setText(subj3);
        Sub3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub3ActionPerformed(evt);
            }
        });

        Sub2.setText(subj2);
        Sub2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub2ActionPerformed(evt);
            }
        });

        Sub1Percentage.setText(subj1Perc+"%");
        Sub1Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub1Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub1Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1PercentageActionPerformed(evt);
            }
        });

        Sub5Percentage.setText(subj5Perc+"%");
        Sub5Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub5Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub5Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub5PercentageActionPerformed(evt);
            }
        });

        Total.setText("Total");
        Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        Sub5.setText(subj5);
        Sub5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub5ActionPerformed(evt);
            }
        });

        Sub4Percentage.setText(subj4Perc+"%");
        Sub4Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub4Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub4Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub4PercentageActionPerformed(evt);
            }
        });

        Sub1.setText(subj1);
        Sub1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1ActionPerformed(evt);
            }
        });

        Sub4.setText(subj4);
        Sub4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub4ActionPerformed(evt);
            }
        });

        TotalPercentage.setText(totalPerc+"%");
        TotalPercentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalPercentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPercentageActionPerformed(evt);
            }
        });

        UsnLabel.setText(USN);
        UsnLabel.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        UsnLabel.setForeground(new java.awt.Color(204, 204, 204));
        UsnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Sub3Percentage.setText(subj3Perc+"%");
        Sub3Percentage.setFont(new java.awt.Font("Tahoma", 1, 24));// NOI18N
        Sub3Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub3Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub3PercentageActionPerformed(evt);
            }
        });

        NameLabel.setText(StudentNameFound);
        NameLabel.setFont(new java.awt.Font("Harlow Solid Italic", 3, 52)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(204, 204, 204));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Sub2Percentage.setText(subj2Perc+"%");
        Sub2Percentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Sub2Percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sub2Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub2PercentageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Total)
                            .addComponent(Sub5)
                            .addComponent(Sub4)
                            .addComponent(Sub3)
                            .addComponent(Sub1)
                            .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sub3Percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(Sub4Percentage)
                            .addComponent(Sub5Percentage)
                            .addComponent(TotalPercentage)
                            .addComponent(Sub2Percentage)
                            .addComponent(Sub1Percentage, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub1Percentage)
                    .addComponent(Sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub2Percentage)
                    .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub3Percentage)
                    .addComponent(Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub4Percentage)
                    .addComponent(Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sub5Percentage)
                    .addComponent(Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane1.setLayer(Sub3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub1Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub5Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Total, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub4Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TotalPercentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(UsnLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub3Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(NameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sub2Percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    
    
    
    
    
    private void Sub1PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub1PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub1PercentageActionPerformed

    private void Sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub1ActionPerformed

    private void Sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub5ActionPerformed

    private void Sub2PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub2PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub2PercentageActionPerformed

    private void Sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub2ActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void Sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub4ActionPerformed

    private void Sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub3ActionPerformed

    private void Sub3PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub3PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub3PercentageActionPerformed

    private void Sub4PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub4PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub4PercentageActionPerformed

    private void Sub5PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub5PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub5PercentageActionPerformed

    private void TotalPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPercentageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckAttendancePercentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckAttendancePercentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckAttendancePercentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckAttendancePercentage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckAttendancePercentage(subj1,subj2,subj3,subj4,subj5,USN).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField Sub1;
    private javax.swing.JTextField Sub1Percentage;
    private javax.swing.JTextField Sub2;
    private javax.swing.JTextField Sub2Percentage;
    private javax.swing.JTextField Sub3;
    private javax.swing.JTextField Sub3Percentage;
    private javax.swing.JTextField Sub4;
    private javax.swing.JTextField Sub4Percentage;
    private javax.swing.JTextField Sub5;
    private javax.swing.JTextField Sub5Percentage;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField TotalPercentage;
    private javax.swing.JLabel UsnLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
